ingress:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  # Routing got too difficult to do here, I even replaced Traefik with Nginx Ingress Controller and it was still a mess
  # Honestly, I'd eventually like another attempt at this but for now this works
  # TLDR is:
  # /api /api/ /api/docs should redirect to web /docs/api
  rules:
    - host: "plutomi.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
    - host: "plutomi.com"
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: "db.plutomi.com"
      http:
        paths:
          # This path is required for Let's Encrypt HTTP-01 challenge
          - path: /.well-known/acme-challenge/
            pathType: Prefix
            backend:
              service:
                # Use existing HTTP service for certificate validation
                name: web
                port:
                  number: 80
  tls:
    - hosts:
        - db.plutomi.com
      secretName: mongodb-tls-secret
