version: "3"
services:
  web:
    container_name: web
    restart: always
    image: plutomi/web:latest
    environment:
      BASE_WEB_URL: ${BASE_WEB_URL}
      BASE_API_URL: ${BASE_API_URL}
      NODE_ENV: production
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "3000:3000"
    env_file:
      - .env
  api:
    container_name: api
    restart: always
    image: plutomi/api:latest
    environment:
      BASE_WEB_URL: ${BASE_WEB_URL}
      BASE_API_URL: ${BASE_API_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_URL: ${DATABASE_URL}
      # Optional
      AXIOM_TOKEN: ${AXIOM_TOKEN}
      AXIOM_DATASET: ${AXIOM_DATASET}
      AXIOM_ORG_ID: ${AXIOM_ORG_ID}

    ports:
      - "8080:8080"
    env_file:
      - .env

  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.25.4
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
