---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgB3xxrRn9aHoAWaUs4roaoDYo8cYeltiozTojX9HAK+LtoRKe//dPrlm4odWw8f4DnX1kdlN5ozWaUl7pdGnQ2ropimzpgrrx3KARDkDY+U+efat8vIjIAkTHeyOadGl09ybVNrJO7ZcS84NGx6XgmEwI8zoG/rZUvaguxoga+2hLsm5GsW0W5T86eqdfEJAzs1GkZ2gZo/eZtKuvunkwe9IhTGEfriK723yAyBlswOyOls6PvMwf+CkgZ45kFRYIzOlaM4tI1ixl71zT2a+QWWJgJSpsZQx0qmpxZI1bmoH++QAtOIgz5qsLogJkH0BFPJ9gVG6nfZ2UMxyLQhR+SvFvMyN+sijQ1FvesHQ+SHwGNhbMhCv+dfem38Quf2RltM1KKeSDvu42CPAHYtjDH/4QXZyZ/GuLrlsJBNuv9hF1W6+oRoaFdQkiILei8D5dVsNLn0Cs7mBpvMNX9QRdP4pYXRZ60kyOQ8YR0UMIHFAiMKAfwoHFulVa1bUJrqxKePKDDsfQXqztBSQftmOIZAFzGDmtXgNiQMwQVobZhd11raYGvPtCrJgwS+69Nomum0RkcWzCrnoCC/KGCxOZ3+e1ouJo9oiM8yZdWHAIJ1nHfSb6ztZzI3AfEiWUdKc9vIP2EuZ4xTRiRbGGqMmhVQrnlqHh126mvkHSVAjKqDyDQJUvEknaEK472d7ZNk3I79zgmSuk1/DvGuv7FoFxzm2gfSwPrPyJCRKoaDr13n7Uk3Fw2gsT2U
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
