apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-cert
  namespace: default
spec:
  secretName: mongodb-tls-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: selfsigned-issuer # Updated to use the self-signed issuer
    kind: ClusterIssuer
  dnsNames:
    - "mongodb.default.svc.cluster.local"
    # To use with port forwarding
    # kubectl port-forward pods/mongodb-0 27017:27017
    - "localhost"
