common:
  ## Readiness probe
  healthCheckPath: /health
  initialDelaySeconds: 10
  periodSeconds: 5
  defaultContainerPort: 80

  ## Rolling update strategy
  maxUnavailable: 0
  maxSurge: 1
  terminationGracePeriodSeconds: 10
  preStopSleepSeconds: 10


  pvc:
    accessModes: ["ReadWriteOnce"]


services:
  api:
    name: api
    port: 3000
  web:
    name: web
    port: 3000 # TODO i think this is wrong value
  mongodb:
    name: mongodb
    port: 27017
