# Must start with 'ingress' key
ingress:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  rules:
    - host: "plutomi.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: "*.plutomi.com" 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
  tls: 
    - hosts:
        - "plutomi.com"
        - "*.plutomi.com" 
      secretName: mongodb-tls-secret


