mongodb:
  name: mongodb
  port: 27017

  initContainer:
    image: busybox
  container:
    image: mongo:7.0.8
    args:
      # TODO restart on cert update cron
      # https://www.mongodb.com/docs/manual/tutorial/configure-ssl/#online-certificate-rotation
      - "--tlsMode=requireTLS"
      - "--tlsCertificateKeyFile=/pem/mongodb.pem"
      # Required now https://jira.mongodb.org/browse/SERVER-72839
      - "--setParameter"
      - "tlsUseSystemCA=true"
      # https://www.mongodb.com/docs/manual/reference/program/mongos/#std-option-mongos.--tlsAllowConnectionsWithoutCertificates
      # Allow clients without certificates to connect - ie disable mTLS, still enables TLS
      # https://stackoverflow.com/a/42870591
      - "--tlsAllowConnectionsWithoutCertificates"
  volumes:
    certSecret: mongodb-tls-secret
    emptyDir: {}
  terminationGracePeriodSeconds: 10
  env:
    MONGO_INITDB_ROOT_USERNAME:
      secretKeyRef:
        name: mongodb-init-secret
        key: MONGO_INITDB_ROOT_USERNAME
    MONGO_INITDB_ROOT_PASSWORD:
      secretKeyRef:
        name: mongodb-init-secret
        key: MONGO_INITDB_ROOT_PASSWORD
  pvc:
    name: mongodb-data
    app: mongodb
    accessModes: ReadWriteOnce
    storage: 10Gi
