{{- with .Values.api }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ $.Values.common.defaultContainerPort }}
      targetPort: {{ .port }}
{{- end}}
