apiVersion: v1
kind: Service
metadata:
  name: { { .Values.api.name } }
spec:
  selector:
    app: { { .Values.api.name } }
  ports:
    - protocol: TCP
      port: { { $.Values.common.defaultContainerPort } }
      targetPort: { { .Values.api.port } }
