apiVersion: v1
kind: Service
metadata:
  name: { { .Values.web.name } }
spec:
  selector:
    app: { { .Values.web.name } }
  ports:
    - protocol: TCP
      # Port the pod listens on
      port: { { $.Values.common.defaultContainerPort } }
      # Port that the service is exposed on
      targetPort: { { .Values.web.port } }
