{{- if .Values.clusterIssuer }}
{{- with .Values.clusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    server: {{ .server }}
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ .secretRef }}
    solvers:
      - http01:
          ingress:
            class: {{ .ingress }}
{{- end }}
{{- end }}
