{{- if .Values.deployments }}
{{- with .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .maxUnavailable }}
      maxSurge: {{ .maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      terminationGracePeriodSeconds: {{ $.Values.common.terminationGracePeriodSeconds }}
      containers:
        {{- range .containers }}
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretKeyRef.name }}
                  key: {{ $value.secretKeyRef.key }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "sleep {{ .preStopSleepSeconds }}",
                  ]
          readinessProbe:
            httpGet:
              path: {{ .healthCheckPath }}
              port: {{ .port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
        {{- end }}
{{- end }}
{{- end }}
