{{- if .Values.deployments }}
{{- range $name, $config := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.name }}
  labels:
    app: {{ $config.name }}
spec:
  replicas: {{ $config.replicas }}
  selector:
    matchLabels:
      app: {{ $config.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $config.maxUnavailable }}
      maxSurge: {{ $config.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ $config.name }}
    spec:
      terminationGracePeriodSeconds: {{ $config.terminationGracePeriodSeconds }}
      containers:
        - name: {{ $config.name }}
          image: {{ $config.image }}
          ports:
            - containerPort: {{ $config.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "sleep {{ $config.preStopSleepSeconds }}",
                  ]
          readinessProbe:
            httpGet:
              path: {{ $config.healthCheckPath }}
              port: {{ $config.port }}
            initialDelaySeconds: {{ $config.initialDelaySeconds }}
            periodSeconds: {{ $config.periodSeconds }}
{{- end }}
{{- end }}
