{{- if .Values.deployment }}
{{- with .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $.Values.common.maxUnavailable }}
      maxSurge: {{ $.Values.common.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      terminationGracePeriodSeconds: {{ $.Values.common.terminationGracePeriodSeconds }}
      containers:
        - name: api
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "sleep {{ $.Values.common.preStopSleepSeconds }}",
                  ]
          readinessProbe:
            httpGet:
              path: {{ $.Values.common.healthCheckPath }}
              port: {{ .port }}
            initialDelaySeconds: {{ $.Values.common.initialDelaySeconds }}
            periodSeconds: {{ $.Values.common.periodSeconds }}
{{- end }}
{{- end }}
