{{- if .Values.pvc }}
{{- with .Values.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    app: {{ .app }}
spec:
  accessModes:
    # Global value from common.yaml
    - {{ $.Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
{{- end }}
