{{- if .Values.services }}
{{- range $name, $config := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.name }}
spec:
  selector:
    app: {{ $config.name }}
  ports:
    - protocol: TCP
      # Port the pod listens on - global value from common.yaml
      port: {{ $config.defaultContainerPort }}
      # Port that the service is exposed on
      targetPort: {{ $config.port }}
{{- end }}
{{- end }}
