{{- if .Values.service }}
{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      # Port the pod listens on - global value from common.yaml
      port: {{ $.Values.common.defaultContainerPort }}
      # Port that the service is exposed on
      targetPort: {{ .port }}
{{- end }}
{{- end }}
