{{- if .Values.databases }}
{{- range $name, $config := .Values.databases }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $config.name }}
spec:
  serviceName: {{ $config.name }}
  replicas: {{ $config.replicas }}
  selector:
    matchLabels:
      app: {{ $config.name }}
  template:
    metadata:
      labels:
        app: {{ $config.name }}
    spec:
      initContainers:
        {{- range $config.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          command:
            {{- range .command }}
            - {{ . }}
            {{- end }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
        {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.common.terminationGracePeriodSeconds }}
      containers:
        {{- range $config.containers }}
        - name: {{ .name }}
          image: {{ $config.image }}
          ports:
            {{- range .ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          env:
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretKeyRef.name }}
                  key: {{ $value.secretKeyRef.key }}
            {{- end }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default true }}
            {{- end }}
          args:
            {{- range .args }}
            - {{ . }}
            {{- end }}
        {{- end }}
      volumes:
        {{- range $config.volumes }}
        - name: {{ .name }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
            items:
              {{- range .secret.items }}
              - key: {{ .key }}
                path: {{ .path }}
              {{- end }}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap.name }}
            items:
              {{- range .configMap.items }}
              - key: {{ .key }}
                path: {{ .path }}
              {{- end }}
          {{- else if .emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
  volumeClaimTemplates:
    {{- range $config.volumeClaimTemplates }}
    - metadata:
        {{- range $key, $value := .metadata }}
        {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
          {{- range $config.pvc.accessModes }}
          - {{ . }}
          {{- end }}
        resources:
          requests:
            storage: {{ .spec.resources.requests.storage }}
    {{- end }}
{{- end }}
{{- end }}
