apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.api }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
  {{- end }}
spec:
  {{- with .Values.api }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .maxUnavailable }}
      maxSurge: {{ .maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
      containers:
        - name: api
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "sleep {{ .preStopSleepSeconds }}",
                  ]
          readinessProbe:
            httpGet:
              path: {{ .healthCheckPath }}
              port: {{ .port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
  {{- end}}
