# Must start with 'databases' key
# This file is subject to change once the operator is brought in
databases:
  name: mongodb
  replicas: 3
  port: 27017
  containers:
    - name: mongodb
      image: mongo:7.0.8
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/mongodb
      command:
        - "mongod"
        - "--replSet"    
        - "rs0"   
        - "--bind_ip_all"    
      # If using a single replica, you can leave the env here
      # And it will be initialized on that one pod and created. If not, you have to manually create the admin user
      env:
        MONGO_INITDB_ROOT_USERNAME:
          secretKeyRef:
            name: mongodb-init-secret
            key: MONGO_INITDB_ROOT_USERNAME
        MONGO_INITDB_ROOT_PASSWORD:
          secretKeyRef:
            name: mongodb-init-secret
            key: MONGO_INITDB_ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        resources:
          requests:
            # On a VPS this won't do much,
            # you'll have access to the entire disk
            storage: 10Gi
