apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      # Port the pod listens on
      port: 80
      # Port that the service is exposed on
      targetPort: 8080
