apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      # Port the pod listens on
      port: 27017
      # Port that the service is exposed on
      targetPort: 27017
