apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      # Port the pod listens on
      port: 80
      # Port that the service is exposed on
      targetPort: 3000
