apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  {{- with .Values.letsencrypt }}
  name: { { .name } }
spec:
  acme:
    server: { { .server } }
    email: { { .email } }
    privateKeySecretRef:
      name: { { .secretRef } }
    solvers:
      - http01:
          ingress:
            class: { { .ingress } }
  {{- end }}
